version: '3'
services:

  mongodb:
    image: mongo:3.2.5
    ports:
      - 27017:27017

  # Interface de Gerênciamento
  mongo-express: 
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - '6379:6379'

  ## Interface de Gerênciamento
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    - PORT=8082
    ports:
    - "8082:8082"