version: '3'
services:

  mongodb:
    image: mongo:3.2.5
    ports:
      - 27017:27017

  mongo-express: # MongoDB Browsers Client
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb