version: '3'

services:
  db:
    image: postgres:latest # Reference: https://docs.docker.com/samples/library/postgres/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs_postgres # nome do database padrão que a imagem cria ao inicializar a primeira vez (Default: POSTGRES_USER)

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080